[deps]
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalOptimisation = "c7c68f13-a4a2-5b9a-b424-07d005f8d9d2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DisplayAs = "0.1"
Documenter = "1"
DocumenterCitations = "1.3"
IntervalArithmetic = "=0.20.9"  # new versions require updates and are incompatible with dependencies
IntervalOptimisation = "0.4"
Plots = "1"
